### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-twitter-ads-source#1]
**Background**
You'll be able to pull up to 45 days of historical data but on an ongoing basis, the integration should pull at a set interval that can be set. Look at the [PRISM repo](https://github.com/aries-data/aries-activity-prism-source/blob/develop/lib/index.js
) for an example of how to use execution date to accomplish this. It will also return a gzip file which will need to be unzipped upon receiving it.

**Requirements**
Using the asynchronous analytics API...
- Allow for user to specify both entities and metric group and then pull in all included metrics
- Allow for [segmentation](https://dev.twitter.com/ads/analytics/metrics-and-segmentation#segmentation) where available.
- Have `start` and `end date` parameters be variable depending on the executionDate (daily window to start)
- Allow for option to pull all historical data

_General_
- Make note of this point in the readme -- `Queries taking over 60 minutes to process with automatically time out.`
- Add todo section to readme with [Derived](https://dev.twitter.com/ads/analytics/metrics-derived) metrics.

**Relevant Links**
https://dev.twitter.com/ads/analytics
https://dev.twitter.com/ads/analytics/best-practices
https://dev.twitter.com/ads/analytics/metrics-and-segmentation#available-metrics-by-metrics-group

**Comment by benjamingregory** [comment]
Waiting on test data

**Comment by austin-toot** [comment]
@jlaneve This needs to have merge conflicts reviewed so a pull request can be made.

**Comment by ryw** [comment]
no more work on aries
